name: Daily Logo Prompt



on:

  workflow_dispatch:

  schedule:

    - cron: '0 3 * * *'



jobs:

  generate:

    runs-on: ubuntu-latest



    steps:

      - name: Checkout

        uses: actions/checkout@v4



      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.13"



      - name: Install dependencies

        run: pip install groq



      - name: Run generator

        env:

          GROQ_API_KEY: ${{ secrets.LRqlhNl91qp2h0WzZF2zWGdyb3FYFi6PrBGud9bSRx5M63jBX3as }}

        run: python generator.py
